### ISSUE TITLE
100% height inner div 

### ISSUE THREAD

**Issue by dum3ng** [dum3ng/study-issues#4]
In many cases we want a 100% height  div of outer container:

```css
.h-100 {
 height: 100%;
}
```

The below example works on some operation system, but not on linux:

```html
<body>
  <div class="main">
    <div class="container">
    </div>
  </div>
</body>
```

```css
body {
  height: 100vh;
  display: flex;
  flex-direction: column;
}
.main {
  flex: 1 0 0;
}
.container {
  background: color;
  height: 100%;
}
```
